# Generated by Django 3.1.7 on 2021-04-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vesit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1)),
                ('iid', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='student-profile')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesit.department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1)),
                ('eid', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='staff-profile')),
                ('staff_type', models.CharField(choices=[('H', 'Head of Department'), ('P', 'Proffesor'), ('A', 'Assistant Proffesor'), ('L', 'Lab incharge'), ('Z', 'Principal')], max_length=1)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesit.department')),
            ],
        ),
    ]
