# Generated by Django 3.1.7 on 2021-04-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210402_1515'),
        ('vesit', '0002_auto_20210402_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceo', to='users.student')),
                ('chair_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('faculty_head1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
                ('faculty_head2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_head2', to='users.staff')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesit.committee')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('H', 'Head'), ('I', 'Incharge')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesit.team')),
            ],
        ),
    ]
