# Generated by Django 3.1.7 on 2021-04-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staff_password'),
        ('vesit', '0003_committee_team_team_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('D', 'Department Level'), ('I', 'Institute Level')], max_length=1)),
                ('location', models.CharField(max_length=100)),
                ('is_approved1', models.BooleanField(default=False)),
                ('is_approved2', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesit.committee')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesit.council')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
