# Generated by Django 3.1.7 on 2021-04-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vesit', '0006_auto_20210403_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vesit.committee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vesit.council'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_approved1',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_approved2',
            field=models.BooleanField(default=None),
        ),
    ]
