# Generated by Django 3.1.7 on 2021-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesit', '0007_auto_20210403_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_approved1',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_approved2',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
