# Generated by Django 3.1.7 on 2021-04-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vesit', '0008_auto_20210403_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vesit.committee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vesit.council'),
        ),
    ]
