# Generated by Django 3.1.7 on 2021-04-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staff_password'),
        ('vesit', '0009_auto_20210403_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_Allowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesit.event')),
            ],
        ),
    ]
